//
// Created by axoford12 on 9/13/17.
//

#ifndef LEVITATE_CONSTS_H
#define LEVITATE_CONSTS_H
#define RAKNET_PROTOCOL  7
enum PacketID{
    ID_CONNECTED_PING_OPEN_CONNECTIONS = 0x01,
    ID_UNCONNECTED_PING_OPEN_CONNECTION = 0x02,
    ID_OPEN_CONNECTION_REQUEST_1 = 0x05,
    ID_OPEN_CONNECTION_REPLY_1 = 0x06,
    ID_OPEN_CONNECTION_REQUEST_2 = 0x07,
    ID_OPEN_CONNECTION_REPLY_2 = 0x08,
    ID_INCOMPATIBLE_PROTOCOL_VERSION = 0x1A,
    ID_UNCONNECTED_PONG_OPEN_CONNECTIONS = 0x1C,
    ID_ADVERTISE_SYSTEM = 0x1D
};

enum CustomPacket{
    CUSTOM_PACKET_0 = 0x80,
    CUSTOM_PACKET_1 = 0x81,
    CUSTOM_PACKET_2 = 0x82,
    CUSTOM_PACKET_3 = 0x83,
    CUSTOM_PACKET_4 = 0x84,
    CUSTOM_PACKET_5 = 0x85,
    CUSTOM_PACKET_6 = 0x86,
    CUSTOM_PACKET_7 = 0x87,
    CUSTOM_PACKET_8 = 0x88,
    CUSTOM_PACKET_9 = 0x89,
    CUSTOM_PACKET_A = 0x8A,
    CUSTOM_PACKET_B = 0x8B,
    CUSTOM_PACKET_C = 0x8C,
    CUSTOM_PACKET_D = 0x8D,
    CUSTOM_PACKET_E = 0x8E,
    CUSTOM_PACKET_F = 0x8F
};
#define ACK  0xC0
#define NACK 0xA0

enum Minecraft{
    MC_PING = 0x00,
    MC_PONG = 0x83,
    MC_CLIENT_CONNECT = 0x09,
    MC_SERVER_HANDSHAKE = 0x10,
    MC_CLINET_HANDSHAKE = 0x13,
    MC_DISCONNECTED_NOTIFICATION = 0x15,
};

#endif //LEVITATE_CONSTS_H
